stages:
  download:
    cmd: python -m model_training.data.download_dataset
    deps:
      - model_training/data/download_dataset.py
    params:
      - data.download
    outs:
      - data/raw

  prepare:
    cmd: python -m model_training.features
    deps:
      - model_training/features.py
      - data/raw
    params:
      - data
    outs:
      - data/processed/features.csv
      - data/processed/bow_vectorizer.pkl
      
  train:
    cmd: python -m model_training.models.train_model
    deps:
      - model_training/models/train_model.py
      - data/processed/features.csv
      - data/processed/bow_vectorizer.pkl
    params:
      - training
    outs:
      - models/model.joblib
    metrics:
      - reports/metrics.json:
          cache: false
      
  evaluate:
    cmd: python -m model_training.models.evaluate_model
    deps:
      - model_training/models/evaluate_model.py
      - models/model.joblib
      - data/processed/features.csv
    metrics:
      - reports/evaluation.json:
          cache: false
          
  prepare_service:
    cmd: python prepare_for_model_service.py
    deps:
      - prepare_for_model_service.py
      - models/model.joblib
    outs:
      - model_service_artifacts 