name: CI Lint & Test

on:
  push:
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Ensure write access for updating README.md

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # (Keeping dummy model_train.py step as requested)
    - name: Create dummy model_train.py to handle unexpected calls
      run: |
        echo "import sys" > model_train.py
        echo "print('WARNING: Dummy model_train.py was executed. This indicates a hardcoded path issue.')" >> model_train.py
        echo "print(f'Arguments passed: {sys.argv[1:]}')" >> model_train.py
        echo "sys.exit(0)" >> model_train.py
        echo "Dummy model_train.py created in repository root."

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Ensure pytest-cov is installed for integrated coverage
        pip install -r requirements.txt
        pip install pylint flake8 bandit pytest coverage pytest-cov dvc[s3]

    - name: Set up DVC and pull data from DagsHub
      run: |
        rm -f .dvc/config*
        dvc remote add -d storage s3://dvc_cloud_setup
        dvc remote modify storage endpointurl https://dagshub.com/api/v1/repo-buckets/s3/s.hakimi
        dvc remote modify storage access_key_id 04dc266bcc211e1d07d5fdfa4f9c999979cf7bb3
        dvc remote modify storage secret_access_key 04dc266bcc211e1d07d5fdfa4f9c999979cf7bb3
        dvc remote modify storage region us-east-1
        dvc pull --force

    - name: Run pylint
      # Pylint command as it was, capturing output for later parsing.
      # The ambiguous option warning remains an external .pylintrc issue.
      run: pylint model_training/ --rcfile=.pylintrc > pylint_report.txt || true

    - name: Run flake8
      run: flake8 model_training/

    - name: Run bandit
      run: bandit -r model_training/

    - name: Run tests with pytest and coverage
      # Use pytest-cov for integrated coverage. -q for quiet output.
      # Redirect output to a file so we can parse the TOTAL coverage in the next step.
      run: |
        pytest -q --cov=model_training --cov-report=term-missing > coverage_report_raw.txt 2>&1
        echo "Raw coverage report saved to coverage_report_raw.txt"

    # --- Start: Metrics Extraction for Plain Text ---
    - name: Extract coverage summary
      id: coverage
      run: |
        # Parse the raw report file to get the TOTAL percentage (e.g., "75%")
        # This should now reliably get the correct percentage from pytest-cov's output.
        total_line=$(grep "TOTAL" coverage_report_raw.txt | awk '{print $NF}')
        echo "percentage=${total_line}" >> $GITHUB_OUTPUT

    - name: Extract pylint score
      id: pylint
      run: |
        # This command remains as before, attempting to extract "9.2/10".
        # If .pylintrc issue prevents this line from being generated, it will remain blank.
        score=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}')
        echo "score=${score}" >> $GITHUB_OUTPUT
    # --- End: Metrics Extraction for Plain Text ---

    - name: Update README with metrics
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        # Replace existing Pylint line (whether badge or previous plain text)
        sed -i -E 's|^(!\[Pylint\].*|Pylint:.*)|Pylint: ${{ steps.pylint.outputs.score }}|g' README.md

        # Replace existing Coverage line (whether badge or previous plain text)
        sed -i -E 's|^(!\[Coverage\].*|Coverage:.*)|Coverage: ${{ steps.coverage.outputs.percentage }}|g' README.md

        git add README.md
        git commit -m "Update coverage and pylint metrics in README" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}