name: Train and Save Model

on:
  push:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Verify files
      run: |
        ls -la  # List all files
        if [ ! -f "model_train.py" ]; then
          echo "❌ model_train.py not found!"
          exit 1
        fi

    - name: Create models directory
      run: mkdir -p models

    - name: Train model
      run: python model_train.py

    - name: Upload models as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ml-models
        path: models/
        retention-days: 7