name: Train Model
on:
  push:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Train model
        run: python train.py
      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-v1
          path: models/