name: Train and Save Model

on:
  push:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install python-dotenv

    - name: Verify directories
      run: |
        ls -la  # List all files
        if [ ! -d "model_training" ]; then
          echo "❌ model_training directory not found!"
          exit 1
        fi

    - name: Create models directory
      run: mkdir -p models

    - name: Train model
      run: python -m model_training.modeling.train

    - name: Rename model files for compatibility
      run: |
        if [ -f "models/bow_vectorizer.pkl" ]; then
          cp models/bow_vectorizer.pkl models/c1_BoW_v1.pkl
        fi
        if [ -f "models/sentiment_classifier.pkl" ]; then
          cp models/sentiment_classifier.pkl models/c2_Classifier_v1.pkl
        fi
        ls -la models/  # List files for verification

    - name: Upload models as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ml-models
        path: models/
        retention-days: 7